// <auto-generated />
namespace Nettbutikk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FromToAttrOIdOrderline : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FromToAttrOIdOrderline));
        
        string IMigrationMetadata.Id
        {
            get { return "201511081941307_From-To-Attr-OIdOrderline"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
